import Crypto
import Foundation

/// HER-254 — embedded `~/.hermes/config.yaml` and `.env` templates used to
/// seed each per-tenant container's `/opt/data/.hermes/` directory before
/// `docker run`. Without a seeded config, Hermes boots with defaults that
/// try to enable telegram/discord/whatsapp/email platforms — all of which
/// fail without credentials and produce noisy logs. We narrow the surface
/// to just the `api_server` platform so the container becomes a clean
/// per-tenant OpenAI-compatible HTTP endpoint.
///
/// Both templates are deterministic given the same `apiKey`. `seed(...)`
/// SHA-256-compares the rendered output against what's on disk and only
/// rewrites on drift, so seeding is idempotent across restarts.
enum HermesTenantConfigTemplate {
    enum SeedError: Swift.Error, Equatable {
        case ioFailure(path: String, underlying: String)
    }

    /// Renders + writes the tenant's `config.yaml` and `.env`. Idempotent:
    /// re-writes only when on-disk SHA-256 differs from the rendered output.
    ///
    /// HER-XXX path fix: Hermes loads `config.yaml` from **HERMES_HOME root**
    /// (`get_config_path()` == `HERMES_HOME/config.yaml` == `/opt/data/config.yaml`),
    /// not `<home>/.hermes/`. The previous `.hermes/config.yaml` location was
    /// silently ignored — the base entrypoint's example copy won instead — so
    /// the narrowed-platform config never took effect. We now write
    /// `config.yaml` at the root so both the platform narrowing AND the
    /// `mcp_servers.mnemosyne` block actually load. (`seed()` runs before every
    /// `docker run`, so existing tenants pick up the corrected config on their
    /// next restart via the drift rewrite.) `.env` is kept under `.hermes/` for
    /// back-compat; `API_SERVER_*` are also injected via `docker --env`, which
    /// Hermes treats as authoritative regardless of the `.env` path.
    static func seed(volumePath: String, apiKey: String, defaultModel: String) throws {
        do {
            try FileManager.default.createDirectory(
                atPath: "\(volumePath)/.hermes",
                withIntermediateDirectories: true,
            )
        } catch {
            throw SeedError.ioFailure(path: "\(volumePath)/.hermes", underlying: String(describing: error))
        }
        try writeIfDrifted(
            path: "\(volumePath)/config.yaml",
            content: configYAML(defaultModel: defaultModel),
        )
        try writeIfDrifted(
            path: "\(volumePath)/.hermes/.env",
            content: envFile(apiKey: apiKey),
        )
    }

    /// Atomic write (write-to-tmp + rename) iff the on-disk SHA-256 differs
    /// from the rendered content. No-op otherwise.
    private static func writeIfDrifted(path: String, content: String) throws {
        let desired = Data(content.utf8)
        let desiredDigest = SHA256.hash(data: desired)

        if let existing = try? Data(contentsOf: URL(fileURLWithPath: path)) {
            let existingDigest = SHA256.hash(data: existing)
            if existingDigest == desiredDigest {
                return
            }
        }

        let tmpPath = "\(path).tmp.\(UUID().uuidString)"
        do {
            try desired.write(to: URL(fileURLWithPath: tmpPath), options: .atomic)
            if FileManager.default.fileExists(atPath: path) {
                _ = try? FileManager.default.removeItem(atPath: path)
            }
            try FileManager.default.moveItem(atPath: tmpPath, toPath: path)
        } catch {
            _ = try? FileManager.default.removeItem(atPath: tmpPath)
            throw SeedError.ioFailure(path: path, underlying: String(describing: error))
        }
    }

    /// Returns the rendered `config.yaml` for a tenant.
    /// - Parameter defaultModel: the model alias served by `/v1/chat/completions`.
    static func configYAML(defaultModel: String) -> String {
        """
        # Auto-generated by HermesContainerManager (HER-254). Do not edit in-place;
        # changes are overwritten on container restart unless the SHA-256 matches.

        model:
          default: "\(defaultModel)"

        platforms:
          api_server:
            enabled: true
            host: 0.0.0.0
            port: 8642
          telegram:
            enabled: false
          discord:
            enabled: false
          whatsapp:
            enabled: false
          slack:
            enabled: false
          matrix:
            enabled: false
          mattermost:
            enabled: false
          email:
            enabled: false

        gateway:
          allow_all_users: true

        logging:
          level: INFO

        # HER-XXX — Mnemosyne memory provider, wired as a Hermes MCP server
        # (top-level `mcp_servers:` is the key this Hermes build reads — see
        # cli-config.yaml.example). Hermes spawns `mnemosyne mcp` (stdio) and
        # auto-discovers its remember/recall/triples tools. The `mnemosyne`
        # console script is baked into the image (docker/hermes.Dockerfile).
        # The per-server `env:` is required: Hermes passes ONLY these (plus safe
        # defaults) to the subprocess, so MNEMOSYNE_DATA_DIR must be set here to
        # land the SQLite store on the persisted /opt/data volume. On by default
        # in every seeded config; `seed()`'s drift rewrite back-fills existing
        # tenants on next restart.
        mcp_servers:
          mnemosyne:
            command: mnemosyne
            args: ["mcp"]
            env:
              MNEMOSYNE_DATA_DIR: /opt/data/mnemosyne
              FASTEMBED_CACHE_PATH: /opt/data/mnemosyne/cache
        """
    }

    /// Returns the rendered `.env` containing only the API_SERVER_KEY.
    /// All other credentials are intentionally absent — they're either
    /// not used by the api_server platform or injected via docker `--env`.
    static func envFile(apiKey: String) -> String {
        """
        # Auto-generated by HermesContainerManager (HER-254).
        API_SERVER_KEY=\(apiKey)
        API_SERVER_ENABLED=true
        API_SERVER_HOST=0.0.0.0
        API_SERVER_PORT=8642
        """
    }
}
