import Crypto
import Foundation

/// HER-254 — embedded `~/.hermes/config.yaml` and `.env` templates used to
/// seed each per-tenant container's `/opt/data/.hermes/` directory before
/// `docker run`. Without a seeded config, Hermes boots with defaults that
/// try to enable telegram/discord/whatsapp/email platforms — all of which
/// fail without credentials and produce noisy logs. We narrow the surface
/// to just the `api_server` platform so the container becomes a clean
/// per-tenant OpenAI-compatible HTTP endpoint.
///
/// Both templates are deterministic given the same `apiKey`. `seed(...)`
/// SHA-256-compares the rendered output against what's on disk and only
/// rewrites on drift, so seeding is idempotent across restarts.
enum HermesTenantConfigTemplate {
    enum SeedError: Swift.Error, Equatable {
        case ioFailure(path: String, underlying: String)
    }

    /// Renders + writes both files into `<volumePath>/.hermes/`. Idempotent:
    /// re-writes only when on-disk SHA-256 differs from the rendered output.
    static func seed(volumePath: String, apiKey: String, defaultModel: String) throws {
        let hermesDir = "\(volumePath)/.hermes"
        do {
            try FileManager.default.createDirectory(
                atPath: hermesDir,
                withIntermediateDirectories: true,
            )
        } catch {
            throw SeedError.ioFailure(path: hermesDir, underlying: String(describing: error))
        }
        try writeIfDrifted(
            path: "\(hermesDir)/config.yaml",
            content: configYAML(defaultModel: defaultModel),
        )
        try writeIfDrifted(
            path: "\(hermesDir)/.env",
            content: envFile(apiKey: apiKey),
        )
    }

    /// Atomic write (write-to-tmp + rename) iff the on-disk SHA-256 differs
    /// from the rendered content. No-op otherwise.
    private static func writeIfDrifted(path: String, content: String) throws {
        let desired = Data(content.utf8)
        let desiredDigest = SHA256.hash(data: desired)

        if let existing = try? Data(contentsOf: URL(fileURLWithPath: path)) {
            let existingDigest = SHA256.hash(data: existing)
            if existingDigest == desiredDigest {
                return
            }
        }

        let tmpPath = "\(path).tmp.\(UUID().uuidString)"
        do {
            try desired.write(to: URL(fileURLWithPath: tmpPath), options: .atomic)
            if FileManager.default.fileExists(atPath: path) {
                _ = try? FileManager.default.removeItem(atPath: path)
            }
            try FileManager.default.moveItem(atPath: tmpPath, toPath: path)
        } catch {
            _ = try? FileManager.default.removeItem(atPath: tmpPath)
            throw SeedError.ioFailure(path: path, underlying: String(describing: error))
        }
    }

    /// Returns the rendered `config.yaml` for a tenant.
    /// - Parameter defaultModel: the model alias served by `/v1/chat/completions`.
    static func configYAML(defaultModel: String) -> String {
        """
        # Auto-generated by HermesContainerManager (HER-254). Do not edit in-place;
        # changes are overwritten on container restart unless the SHA-256 matches.

        model:
          default: "\(defaultModel)"

        platforms:
          api_server:
            enabled: true
            host: 0.0.0.0
            port: 8642
          telegram:
            enabled: false
          discord:
            enabled: false
          whatsapp:
            enabled: false
          slack:
            enabled: false
          matrix:
            enabled: false
          mattermost:
            enabled: false
          email:
            enabled: false

        gateway:
          allow_all_users: true

        logging:
          level: INFO

        # HER-XXX — Mnemosyne memory provider, wired as an MCP server. Hermes
        # spawns `mnemosyne mcp` (stdio) and registers its remember/recall/
        # triples tools as native commands. The `mnemosyne` console script is
        # baked into the image (docker/hermes.Dockerfile); the SQLite store
        # persists on the per-tenant volume via MNEMOSYNE_DATA_DIR=/opt/data/mnemosyne
        # (injected as a container env). Present in every seeded config so
        # memory is on by default; `seed()`'s SHA-256 drift rewrite back-fills
        # this block into existing tenants on their next restart.
        mcp:
          servers:
            mnemosyne:
              command: mnemosyne
              args: ["mcp"]
        """
    }

    /// Returns the rendered `.env` containing only the API_SERVER_KEY.
    /// All other credentials are intentionally absent — they're either
    /// not used by the api_server platform or injected via docker `--env`.
    static func envFile(apiKey: String) -> String {
        """
        # Auto-generated by HermesContainerManager (HER-254).
        API_SERVER_KEY=\(apiKey)
        API_SERVER_ENABLED=true
        API_SERVER_HOST=0.0.0.0
        API_SERVER_PORT=8642
        """
    }
}
