import FluentKit
import SQLKit

/// Recent Settings → Diagnostics events generated by unified connection
/// checks. The event body is normalized for client display; detailed subsystem
/// state remains in provider/gateway/calendar tables.
struct M87_CreateConnectionDiagnosticEvents: AsyncMigration {
    func prepare(on database: any Database) async throws {
        try await database.schema(ConnectionDiagnosticEvent.schema)
            .id()
            .field("tenant_id", .uuid, .required,
                   .references(User.schema, "id", onDelete: .cascade))
            .field("occurred_at", .datetime, .required)
            .field("kind", .string, .required)
            .field("connection_id", .string)
            .field("connection_title", .string)
            .field("severity", .string, .required)
            .field("message", .string, .required)
            .field("code", .string)
            .field("created_at", .datetime)
            .create()

        guard let sql = database as? any SQLDatabase else { return }
        try await sql.raw(#"""
        CREATE INDEX IF NOT EXISTS connection_diagnostic_events_tenant_occurred_idx
        ON connection_diagnostic_events(tenant_id, occurred_at DESC)
        """#).run()
    }

    func revert(on database: any Database) async throws {
        try await database.schema(ConnectionDiagnosticEvent.schema).delete()
    }
}
