#!/bin/bash
# Generic setup script template for community Hermes skills
# This template is idempotent — safe to re-run multiple times

set -e  # Exit on error (comment out for debugging)

# ============================================================
# CONFIGURATION — customize these for your skill
# ============================================================

SKILL_NAME="community-skill"
REPO_URL="https://github.com/owner/repo.git"
CLONE_DIR="${HOME}/${SKILL_NAME}-full"
# Python dependencies (space-separated list)
PYTHON_DEPS="package1 package2"
# System packages (for apt/dnf/brew)
SYS_DEPS="binary1 binary2"
# Environment variables required (will prompt if missing)
REQUIRED_ENV_VARS=("API_KEY" "CONFIG_PATH")
# Cron job pattern (optional)
CRON_PATTERN="0 2 * * * cd ${CLONE_DIR} && python3 script.py --run"
CRON_IDENT="hermes-${SKILL_NAME}"

# ============================================================
# PREREQUISITE CHECK
# ============================================================

echo "=== ${SKILL_NAME} Setup ==="

# Check for required env vars
MISSING_VARS=()
for var in "${REQUIRED_ENV_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        MISSING_VARS+=("$var")
    fi
done

if [ ${#MISSING_VARS[@]} -gt 0 ]; then
    echo "⚠️  Missing environment variables: ${MISSING_VARS[*]}"
    echo "   Set them before continuing:"
    for var in "${MISSING_VARS[@]}"; do
        echo "     export ${var}=your_value_here"
    done
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# ============================================================
# STEP 1: Clone repository (idempotent)
# ============================================================

echo ""
echo "Step 1: Cloning repository..."

if [ -d "$CLONE_DIR" ]; then
    echo "✓ Already cloned at $CLONE_DIR"
    echo "   Updating to latest..."
    git -C "$CLONE_DIR" pull || echo "⚠️  Pull failed — check git status"
else
    git clone "$REPO_URL" "$CLONE_DIR"
    echo "✓ Cloned to $CLONE_DIR"
fi

# ============================================================
# STEP 2: Install system dependencies
# ============================================================

if [ -n "$SYS_DEPS" ]; then
    echo ""
    echo "Step 2: Installing system packages..."

    if command -v apt-get &>/dev/null; then
        sudo apt-get update
        sudo apt-get install -y $SYS_DEPS
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y $SYS_DEPS
    elif command -v brew &>/dev/null; then
        brew install $SYS_DEPS
    else
        echo "❌ Unknown package manager. Install manually: $SYS_DEPS"
    fi
fi

# ============================================================
# STEP 3: Install Python dependencies
# ============================================================

if [ -n "$PYTHON_DEPS" ]; then
    echo ""
    echo "Step 3: Installing Python packages..."

    # Prefer Hermes venv pip if it exists and is usable
    if [ -f /opt/hermes/.venv/bin/pip ]; then
        echo "   → Using Hermes venv pip"
        sudo /opt/hermes/.venv/bin/pip install $PYTHON_DEPS || {
            echo "⚠️  Hermes venv pip failed (permission?) — falling back to user install"
            python3 -m pip install --user $PYTHON_DEPS
        }
    else
        echo "   → Using system Python (--user)"
        python3 -m pip install --user $PYTHON_DEPS
    fi
fi

# ============================================================
# STEP 4: Create configuration directories
# ============================================================

echo ""
echo "Step 4: Creating configuration directories..."

# Customize per-skill below:
mkdir -p "${HOME}/.${SKILL_NAME}"
mkdir -p "${HOME}/assets/data"     # Common pattern
mkdir -p "${HOME}/assets/output"   # Common pattern

# Example config file generation:
CONFIG_FILE="${HOME}/.${SKILL_NAME}/config.yaml"
if [ ! -f "$CONFIG_FILE" ]; then
    cat > "$CONFIG_FILE" <<EOF
# ${SKILL_NAME} configuration
# Generated by setup script
skill:
  name: "${SKILL_NAME}"
  repo: "${CLONE_DIR}"
output:
  directory: "${HOME}/assets/output"
EOF
    echo "✓ Created config: $CONFIG_FILE"
else
    echo "✓ Config already exists: $CONFIG_FILE"
fi

# ============================================================
# STEP 5: Update Hermes config (if applicable)
# ============================================================

HERMES_CONFIG="${HOME}/.hermes/config.yaml"
if [ -f "$HERMES_CONFIG" ]; then
    echo ""
    echo "Step 5: Checking Hermes config integration..."

    # Example: add a path entry if not present
    if ! grep -q "${SKILL_NAME}_path" "$HERMES_CONFIG"; then
        echo "" >> "$HERMES_CONFIG"
        echo "# ${SKILL_NAME} integration" >> "$HERMES_CONFIG"
        echo "${SKILL_NAME}_path: \"${CLONE_DIR}/scripts\"" >> "$HERMES_CONFIG"
        echo "✓ Updated $HERMES_CONFIG"
    else
        echo "✓ Hermes config already has ${SKILL_NAME}_path entry"
    fi
else
    echo "⚠️  No Hermes config found at $HERMES_CONFIG — skipping integration"
fi

# ============================================================
# STEP 6: Install cron job (optional)
# ============================================================

if [ -n "$CRON_PATTERN" ]; then
    echo ""
    echo "Step 6: Installing cron job..."

    if ! crontab -l 2>/dev/null | grep -q "$CRON_IDENT"; then
        (crontab -l 2>/dev/null; echo "$CRON_PATTERN") | crontab -
        echo "✓ Cron job added (runs automatically)"
    else
        echo "✓ Cron job already present"
    fi
fi

# ============================================================
# DONE
# ============================================================

echo ""
echo "✅ ${SKELL_NAME} setup complete!"
echo ""
echo "Next steps:"
echo "  1. Verify: python3 ${CLONE_DIR}/scripts/$(basename ${CLONE_DIR}).py --help"
echo "  2. Restart Hermes: hermes restart"
echo "  3. Test in chat: try a trigger phrase"
echo ""
echo "Documentation:"
echo "  Vault: Raw/Dev/$(date +%Y-%m-%d) — GitHub - ${SKILL_NAME} - README.md"
echo "  Original: ${REPO_URL}"