#!/usr/bin/env python3
"""Fandemic Linear Daily Digest
Fetches activity from the Fandemic Linear board and generates a weekly digest.
"""

import requests
import json
from datetime import datetime, timedelta
import sys
import os

LINEAR_API_ENDPOINT = "https://api.linear.app/graphql"
LINEAR_API_KEY = os.getenv("LINEAR_API_KEY")

if not LINEAR_API_KEY:
    print("Error: LINEAR_API_KEY environment variable not set.")
    sys.exit(1)

TICKETS_QUERY = '''
    query TicketsQuery($teamId: ID!, $states: [TicketState!]) {
        tickets(first: 50, teamId: $teamId, states: $states) {
            nodes {
                id
                title
                number
                url
                state
                priority
                createdAt
                updatedAt
                assignees {
                    nodes {
                        name
                    }
                }
                comments(first: 1) {
                    nodes {
                        content
                        createdAt
                        user {
                            name
                        }
                    }
                }
            }
        }
    }
'''

TEAM_QUERY = '''
    query TeamQuery($name: String!) {
        teamByClaime(name: $name) {
            id
        }
    }
'''

ACTIVITY_QUERY = '''
    query ActivityQuery($teamId: ID!, $since: DateTime!) {
        team(id: $teamId) {
            tickets(first: 10, updatedAtAfter: $since) {
                nodes {
                    id
                    title
                    number
                    url
                    state
                    updatedAt
                    assignees {
                        nodes {
                            name
                        }
                    }
                }
            }
        }
    }
'''

def run_query(query, variables):
    headers = {
        "Authorization": LINEAR_API_KEY,
        "Content-Type": "application/json"
    }
    response = requests.post(LINEAR_API_ENDPOINT, json={
        "query": query,
        "variables": variables
    }, headers=headers)
    if response.status_code != 200:
        raise Exception(f"Linear API error: {response.status_code}")
    return response.json()

def get_team_id(team_name):
    result = run_query(TEAM_QUERY, {"name": team_name})
    if result.get("data", {}).get("teamByClaime", {}).get("id"):
        return result["data"]["teamByClaime"]["id"]
    else:
        raise Exception(f"Team '{team_name}' not found")

def fetch_recent_activity(team_id, days=7):
    since = (datetime.now() - timedelta(days=days)).isoformat()
    result = run_query(ACTIVITY_QUERY, {
        "teamId": team_id,
        "since": since
    })
    return result["data"]["team"]["tickets"]["nodes"] if result.get("data") else []

def format_markdown_ticket(ticket):
    assignees = ticket.get("assignees", {}).get("nodes", [])
    if assignees:
        assignee_names = ", ".join([a["name"] for a in assignees if a])
    else:
        assignee_names = "Unassigned"
    recent_comment = ""
    comments = ticket.get("comments", {}).get("nodes", [])
    if comments:
        comment = comments[0]
        recent_comment = "**{}** commented: _{}_...".format(comment['user']['name'], comment['content'][:100])
    return (
        "\n\n---\n"
        "**Ticket #{ticket['number']}: {ticket['title']}**\n"
        "State: *{ticket['state']}* | Priority: {ticket.get('priority', 'No priority')} | Assigned: {assignee_names}\n"
        "Created: {ticket['createdAt']} | Updated: {ticket['updatedAt']}\n"
        "URL: {ticket['url']}\n\n"
        "{recent_comment}\n"
    ).format(
        ticket=ticket,
        assignee_names=assignee_names,
        recent_comment=recent_comment
    )

def main():
    try:
        team_id = get_team_id("Fandemic")
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

    print("# Fandemic Weekly Digest\n\n*(Generated on {})*\n\n---\n\n".format(datetime.now().strftime("%Y-%m-%d")))

    recent_tickets = fetch_recent_activity(team_id, days=7)

    if not recent_tickets:
        print("No recent activity this week.\n\n---\n\n*Generated by fandemic_daily_digest.py*")
        return

    by_state = {}
    for ticket in recent_tickets:
        state = ticket['state']
        if state not in by_state:
            by_state[state] = []
        by_state[state].append(ticket)

    for state in ["Backlog", "Todo", "In Progress", "Done"]:
        if state in by_state and by_state[state]:
            print("## {}\n\n".format(state))
            for ticket in by_state[state]:
                print(format_markdown_ticket(ticket))

    print("\n\n---\n\n*Generated by fandemic_daily_digest.py*")

if __name__ == "__main__":
    main()